name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Check if Build Script Exists
        run: |
          cd backend
          if ! npm run | grep -q "build"; then
            echo "No build script found. Skipping build step."
          else
            npm run build
          fi

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run ESLint (Checks for Errors & Warnings)
        run: |
          cd frontend
          npm run lint || echo "ESLint warnings found, but continuing."

      - name: Build Frontend (Disables Warnings as Errors)
        run: |
          cd frontend
          CI=false npm run build
